// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableData.proto

package com.elex.hoe.table;

public final class TableDataOuterClass {
  private TableDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TableDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elex.hoe.table.TableData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    boolean hasDemoTableData();
    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    com.elex.hoe.table.DemoTableOuterClass.DemoTable getDemoTableData();
    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder getDemoTableDataOrBuilder();

    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    boolean hasActionTableData();
    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    com.elex.hoe.table.ActionTableOuterClass.ActionTable getActionTableData();
    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder getActionTableDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.elex.hoe.table.TableData}
   */
  public  static final class TableData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elex.hoe.table.TableData)
      TableDataOrBuilder {
    // Use TableData.newBuilder() to construct.
    private TableData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TableData() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TableData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder subBuilder = null;
              if (demoTableData_ != null) {
                subBuilder = demoTableData_.toBuilder();
              }
              demoTableData_ = input.readMessage(com.elex.hoe.table.DemoTableOuterClass.DemoTable.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(demoTableData_);
                demoTableData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder subBuilder = null;
              if (actionTableData_ != null) {
                subBuilder = actionTableData_.toBuilder();
              }
              actionTableData_ = input.readMessage(com.elex.hoe.table.ActionTableOuterClass.ActionTable.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actionTableData_);
                actionTableData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.hoe.table.TableDataOuterClass.internal_static_com_elex_hoe_table_TableData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.hoe.table.TableDataOuterClass.internal_static_com_elex_hoe_table_TableData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.hoe.table.TableDataOuterClass.TableData.class, com.elex.hoe.table.TableDataOuterClass.TableData.Builder.class);
    }

    public static final int DEMOTABLEDATA_FIELD_NUMBER = 1;
    private com.elex.hoe.table.DemoTableOuterClass.DemoTable demoTableData_;
    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    public boolean hasDemoTableData() {
      return demoTableData_ != null;
    }
    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    public com.elex.hoe.table.DemoTableOuterClass.DemoTable getDemoTableData() {
      return demoTableData_ == null ? com.elex.hoe.table.DemoTableOuterClass.DemoTable.getDefaultInstance() : demoTableData_;
    }
    /**
     * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
     */
    public com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder getDemoTableDataOrBuilder() {
      return getDemoTableData();
    }

    public static final int ACTIONTABLEDATA_FIELD_NUMBER = 2;
    private com.elex.hoe.table.ActionTableOuterClass.ActionTable actionTableData_;
    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    public boolean hasActionTableData() {
      return actionTableData_ != null;
    }
    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    public com.elex.hoe.table.ActionTableOuterClass.ActionTable getActionTableData() {
      return actionTableData_ == null ? com.elex.hoe.table.ActionTableOuterClass.ActionTable.getDefaultInstance() : actionTableData_;
    }
    /**
     * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
     */
    public com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder getActionTableDataOrBuilder() {
      return getActionTableData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (demoTableData_ != null) {
        output.writeMessage(1, getDemoTableData());
      }
      if (actionTableData_ != null) {
        output.writeMessage(2, getActionTableData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (demoTableData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDemoTableData());
      }
      if (actionTableData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getActionTableData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.hoe.table.TableDataOuterClass.TableData)) {
        return super.equals(obj);
      }
      com.elex.hoe.table.TableDataOuterClass.TableData other = (com.elex.hoe.table.TableDataOuterClass.TableData) obj;

      boolean result = true;
      result = result && (hasDemoTableData() == other.hasDemoTableData());
      if (hasDemoTableData()) {
        result = result && getDemoTableData()
            .equals(other.getDemoTableData());
      }
      result = result && (hasActionTableData() == other.hasActionTableData());
      if (hasActionTableData()) {
        result = result && getActionTableData()
            .equals(other.getActionTableData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDemoTableData()) {
        hash = (37 * hash) + DEMOTABLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getDemoTableData().hashCode();
      }
      if (hasActionTableData()) {
        hash = (37 * hash) + ACTIONTABLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getActionTableData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.hoe.table.TableDataOuterClass.TableData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.hoe.table.TableDataOuterClass.TableData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elex.hoe.table.TableData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elex.hoe.table.TableData)
        com.elex.hoe.table.TableDataOuterClass.TableDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.hoe.table.TableDataOuterClass.internal_static_com_elex_hoe_table_TableData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.hoe.table.TableDataOuterClass.internal_static_com_elex_hoe_table_TableData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.hoe.table.TableDataOuterClass.TableData.class, com.elex.hoe.table.TableDataOuterClass.TableData.Builder.class);
      }

      // Construct using com.elex.hoe.table.TableDataOuterClass.TableData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (demoTableDataBuilder_ == null) {
          demoTableData_ = null;
        } else {
          demoTableData_ = null;
          demoTableDataBuilder_ = null;
        }
        if (actionTableDataBuilder_ == null) {
          actionTableData_ = null;
        } else {
          actionTableData_ = null;
          actionTableDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.hoe.table.TableDataOuterClass.internal_static_com_elex_hoe_table_TableData_descriptor;
      }

      public com.elex.hoe.table.TableDataOuterClass.TableData getDefaultInstanceForType() {
        return com.elex.hoe.table.TableDataOuterClass.TableData.getDefaultInstance();
      }

      public com.elex.hoe.table.TableDataOuterClass.TableData build() {
        com.elex.hoe.table.TableDataOuterClass.TableData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.hoe.table.TableDataOuterClass.TableData buildPartial() {
        com.elex.hoe.table.TableDataOuterClass.TableData result = new com.elex.hoe.table.TableDataOuterClass.TableData(this);
        if (demoTableDataBuilder_ == null) {
          result.demoTableData_ = demoTableData_;
        } else {
          result.demoTableData_ = demoTableDataBuilder_.build();
        }
        if (actionTableDataBuilder_ == null) {
          result.actionTableData_ = actionTableData_;
        } else {
          result.actionTableData_ = actionTableDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.hoe.table.TableDataOuterClass.TableData) {
          return mergeFrom((com.elex.hoe.table.TableDataOuterClass.TableData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.hoe.table.TableDataOuterClass.TableData other) {
        if (other == com.elex.hoe.table.TableDataOuterClass.TableData.getDefaultInstance()) return this;
        if (other.hasDemoTableData()) {
          mergeDemoTableData(other.getDemoTableData());
        }
        if (other.hasActionTableData()) {
          mergeActionTableData(other.getActionTableData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.hoe.table.TableDataOuterClass.TableData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.hoe.table.TableDataOuterClass.TableData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.elex.hoe.table.DemoTableOuterClass.DemoTable demoTableData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.hoe.table.DemoTableOuterClass.DemoTable, com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder, com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder> demoTableDataBuilder_;
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public boolean hasDemoTableData() {
        return demoTableDataBuilder_ != null || demoTableData_ != null;
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public com.elex.hoe.table.DemoTableOuterClass.DemoTable getDemoTableData() {
        if (demoTableDataBuilder_ == null) {
          return demoTableData_ == null ? com.elex.hoe.table.DemoTableOuterClass.DemoTable.getDefaultInstance() : demoTableData_;
        } else {
          return demoTableDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public Builder setDemoTableData(com.elex.hoe.table.DemoTableOuterClass.DemoTable value) {
        if (demoTableDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          demoTableData_ = value;
          onChanged();
        } else {
          demoTableDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public Builder setDemoTableData(
          com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder builderForValue) {
        if (demoTableDataBuilder_ == null) {
          demoTableData_ = builderForValue.build();
          onChanged();
        } else {
          demoTableDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public Builder mergeDemoTableData(com.elex.hoe.table.DemoTableOuterClass.DemoTable value) {
        if (demoTableDataBuilder_ == null) {
          if (demoTableData_ != null) {
            demoTableData_ =
              com.elex.hoe.table.DemoTableOuterClass.DemoTable.newBuilder(demoTableData_).mergeFrom(value).buildPartial();
          } else {
            demoTableData_ = value;
          }
          onChanged();
        } else {
          demoTableDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public Builder clearDemoTableData() {
        if (demoTableDataBuilder_ == null) {
          demoTableData_ = null;
          onChanged();
        } else {
          demoTableData_ = null;
          demoTableDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder getDemoTableDataBuilder() {
        
        onChanged();
        return getDemoTableDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      public com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder getDemoTableDataOrBuilder() {
        if (demoTableDataBuilder_ != null) {
          return demoTableDataBuilder_.getMessageOrBuilder();
        } else {
          return demoTableData_ == null ?
              com.elex.hoe.table.DemoTableOuterClass.DemoTable.getDefaultInstance() : demoTableData_;
        }
      }
      /**
       * <code>.com.elex.hoe.table.DemoTable DemoTableData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.hoe.table.DemoTableOuterClass.DemoTable, com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder, com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder> 
          getDemoTableDataFieldBuilder() {
        if (demoTableDataBuilder_ == null) {
          demoTableDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.elex.hoe.table.DemoTableOuterClass.DemoTable, com.elex.hoe.table.DemoTableOuterClass.DemoTable.Builder, com.elex.hoe.table.DemoTableOuterClass.DemoTableOrBuilder>(
                  getDemoTableData(),
                  getParentForChildren(),
                  isClean());
          demoTableData_ = null;
        }
        return demoTableDataBuilder_;
      }

      private com.elex.hoe.table.ActionTableOuterClass.ActionTable actionTableData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.hoe.table.ActionTableOuterClass.ActionTable, com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder, com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder> actionTableDataBuilder_;
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public boolean hasActionTableData() {
        return actionTableDataBuilder_ != null || actionTableData_ != null;
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public com.elex.hoe.table.ActionTableOuterClass.ActionTable getActionTableData() {
        if (actionTableDataBuilder_ == null) {
          return actionTableData_ == null ? com.elex.hoe.table.ActionTableOuterClass.ActionTable.getDefaultInstance() : actionTableData_;
        } else {
          return actionTableDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public Builder setActionTableData(com.elex.hoe.table.ActionTableOuterClass.ActionTable value) {
        if (actionTableDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actionTableData_ = value;
          onChanged();
        } else {
          actionTableDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public Builder setActionTableData(
          com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder builderForValue) {
        if (actionTableDataBuilder_ == null) {
          actionTableData_ = builderForValue.build();
          onChanged();
        } else {
          actionTableDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public Builder mergeActionTableData(com.elex.hoe.table.ActionTableOuterClass.ActionTable value) {
        if (actionTableDataBuilder_ == null) {
          if (actionTableData_ != null) {
            actionTableData_ =
              com.elex.hoe.table.ActionTableOuterClass.ActionTable.newBuilder(actionTableData_).mergeFrom(value).buildPartial();
          } else {
            actionTableData_ = value;
          }
          onChanged();
        } else {
          actionTableDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public Builder clearActionTableData() {
        if (actionTableDataBuilder_ == null) {
          actionTableData_ = null;
          onChanged();
        } else {
          actionTableData_ = null;
          actionTableDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder getActionTableDataBuilder() {
        
        onChanged();
        return getActionTableDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      public com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder getActionTableDataOrBuilder() {
        if (actionTableDataBuilder_ != null) {
          return actionTableDataBuilder_.getMessageOrBuilder();
        } else {
          return actionTableData_ == null ?
              com.elex.hoe.table.ActionTableOuterClass.ActionTable.getDefaultInstance() : actionTableData_;
        }
      }
      /**
       * <code>.com.elex.hoe.table.ActionTable ActionTableData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.hoe.table.ActionTableOuterClass.ActionTable, com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder, com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder> 
          getActionTableDataFieldBuilder() {
        if (actionTableDataBuilder_ == null) {
          actionTableDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.elex.hoe.table.ActionTableOuterClass.ActionTable, com.elex.hoe.table.ActionTableOuterClass.ActionTable.Builder, com.elex.hoe.table.ActionTableOuterClass.ActionTableOrBuilder>(
                  getActionTableData(),
                  getParentForChildren(),
                  isClean());
          actionTableData_ = null;
        }
        return actionTableDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.elex.hoe.table.TableData)
    }

    // @@protoc_insertion_point(class_scope:com.elex.hoe.table.TableData)
    private static final com.elex.hoe.table.TableDataOuterClass.TableData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.hoe.table.TableDataOuterClass.TableData();
    }

    public static com.elex.hoe.table.TableDataOuterClass.TableData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TableData>
        PARSER = new com.google.protobuf.AbstractParser<TableData>() {
      public TableData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TableData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TableData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TableData> getParserForType() {
      return PARSER;
    }

    public com.elex.hoe.table.TableDataOuterClass.TableData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elex_hoe_table_TableData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elex_hoe_table_TableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TableData.proto\022\022com.elex.hoe.table\032\017D" +
      "emoTable.proto\032\021ActionTable.proto\"{\n\tTab" +
      "leData\0224\n\rDemoTableData\030\001 \001(\0132\035.com.elex" +
      ".hoe.table.DemoTable\0228\n\017ActionTableData\030" +
      "\002 \001(\0132\037.com.elex.hoe.table.ActionTableb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.elex.hoe.table.DemoTableOuterClass.getDescriptor(),
          com.elex.hoe.table.ActionTableOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_elex_hoe_table_TableData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elex_hoe_table_TableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elex_hoe_table_TableData_descriptor,
        new java.lang.String[] { "DemoTableData", "ActionTableData", });
    com.elex.hoe.table.DemoTableOuterClass.getDescriptor();
    com.elex.hoe.table.ActionTableOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
